"""add_navigation_items_and_plan_features

Revision ID: de9e9ee26559
Revises: 50c61a925f87
Create Date: 2026-09-18 15:13:41.201718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de9e9ee26559'
down_revision: Union[str, Sequence[str], None] = '50c61a925f87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('navigation_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('menu_type', sa.String(length=50), server_default='top_navbar', nullable=False),
    sa.Column('target_role', sa.String(length=50), server_default='all', nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_navigation_items_menu_type'), 'navigation_items', ['menu_type'], unique=False)
    op.create_index(op.f('ix_navigation_items_target_role'), 'navigation_items', ['target_role'], unique=False)
    op.add_column('plans', sa.Column('features', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'features')
    op.drop_index(op.f('ix_navigation_items_target_role'), table_name='navigation_items')
    op.drop_index(op.f('ix_navigation_items_menu_type'), table_name='navigation_items')
    op.drop_table('navigation_items')
    # ### end Alembic commands ###
